### ISSUE TITLE
Background text overlaps date display

### ISSUE THREAD

**Issue by sling-shot** [Dr-42/AnalogueGrandClock#1]
This is a much needed enhancement, but unfortunately the date is displayed above "Community Design' text or vice versa.

Is it possible to move the date-day display to the traditional 3 o'clock position as seen in wrist watches?

**Comment by Dr-42** [comment]
Hi... Thanks for using my widget!! I didn't know anyone else was using it.

Well That could be done and I could expose an option in the kirigami settings for the app. But I wrote this so long ago that I don't exactly remeber how it works. I will try though.

But the issue I see on a quick look at the code is that if I move it to 3o' clock, then the text might cross the center. So, that would also require font size adjustment.

Also, quick question, does the gong sound play every hour for you? I don't think it does because I seem to have hard coded the path to a non asset path.

**Comment by Dr-42** [comment]
Accidentally closed the issue. Don't mind it

**Comment by sling-shot** [comment]
I had just installed it yesterday after trying an experimental build with KDE Plasma 6. Now that you have mentioned it, I have not heard the gong sound.

Where is the source for the background with the 'Community Design' text? If possible changing that might be a better solution.

**Comment by Dr-42** [comment]
The background actually depends on your theme. Anyways I figured it all out and I have made both the position and the font size configurable and fixed the gong sound too. You can access all this in the widget's settings.

**Comment by Dr-42** [comment]
Star the repo if you like the fix!!
